In [3]:
import pandas as pd

df = pd.read_csv("input-pmdcmd-gdp.csv")
df[:10]

,Period,Reference Area,Industry Section,Measure Type,Unit,Value
0,year/2012,http://data.europa.eu/nuts/code/UKC,a_t,gdp-from-gva,indices,97.916263
1,year/2012,http://data.europa.eu/nuts/code/UKD,a_t,gdp-from-gva,indices,92.315793
2,year/2012,http://data.europa.eu/nuts/code/UKE,a_t,gdp-from-gva,indices,95.050427
3,year/2012,http://data.europa.eu/nuts/code/UKF,a_t,gdp-from-gva,indices,92.477318
4,year/2012,http://data.europa.eu/nuts/code/UKG,a_t,gdp-from-gva,indices,89.813255
5,year/2012,http://data.europa.eu/nuts/code/UKH,a_t,gdp-from-gva,indices,89.626843
6,year/2012,http://data.europa.eu/nuts/code/UKI,a_t,gdp-from-gva,indices,87.837338
7,year/2012,http://data.europa.eu/nuts/code/UKJ,a_t,gdp-from-gva,indices,92.545869
8,year/2012,http://data.europa.eu/nuts/code/UKK,a_t,gdp-from-gva,indices,92.796948
9,year/2012,http://statistics.data.gov.uk/id/statistical-g...,a_t,gdp-from-gva,indices,91.098020

In [5]:
df["Reference Area"] = df["Reference Area"].map(lambda x: x.split("/")[-1])
df[:10]

df["Period"] = df["Period"].map(lambda x: x.split("/")[-1])
df[:10]

  Period Reference Area Industry Section  Measure Type     Unit      Value
0   2012            UKC              a_t  gdp-from-gva  indices  97.916263
1   2012            UKD              a_t  gdp-from-gva  indices  92.315793
2   2012            UKE              a_t  gdp-from-gva  indices  95.050427
3   2012            UKF              a_t  gdp-from-gva  indices  92.477318
4   2012            UKG              a_t  gdp-from-gva  indices  89.813255
5   2012            UKH              a_t  gdp-from-gva  indices  89.626843
6   2012            UKI              a_t  gdp-from-gva  indices  87.837338
7   2012            UKJ              a_t  gdp-from-gva  indices  92.545869
8   2012            UKK              a_t  gdp-from-gva  indices  92.796948
9   2012      E92000001              a_t  gdp-from-gva  indices  91.098020

In [ ]:
df.to_csv('input-pmdcmd-gdp.csv', index=False)